/************************************************************************ 
Author : Sukku
Details: 
    Purpose : MobileCalendarHandler is the apex class to fetch the data from MobileCalendarConfig__mdt and return 
              a wrapper response to mobilecalendar Web component. 
    Intial release date : August 01, 2020 

Powered by Cloud Sloka Pty Ltd. "www.cloudsloka.com.au"
*************************************************************************/
public virtual class roITriggerHandler{
     
    public virtual void beforeInsert(List<sObject> newList){

    }
     
    public virtual void afterInsert(Map<Id, sObject> newMap){

    }
     
    public virtual void beforeUpdate(Map<Id, sObject> newMap, Map<Id, sObject> oldMap){

    }
    
    public virtual void afterUpdate(Map<Id, sObject> newMap, Map<Id, sObject> oldMap){

    }

    public virtual void beforeDelete(Map<Id, sObject> oldMap){

    }
     
    public virtual void afterDelete(Map<Id, sObject> oldMap){

    }
}